# -*- coding: utf-8 -*-
"""
Segments_Fill_config_V1.py is the configuration file for Segments_Fill_V1.py.

One chromosome is processed at a time.

1) Make manual edits to the .xlsx file generated by Visual Phaser and save.
   Make sure that RP assignments are correct.
   
2) Run Segments_Fill_V1.py

3) The program calculates the column widths and generates a map of segment 
   colors.
   
4) Using this color map, the colors of the chromosomes in each segment are 
   calculated. If colors cannot be calculated, the segment is left blank.

5) Increase resolution if segments too small to be correctly classified. 

6) Use START_SIB = "Auto" for initial run. Try other sibs if you think you can
   do better! 

7) Choose a column to start calculations. The default is "H". You might get 
   better results by stating at a different column.    

© 2026 Mick Jolley (mickj1948@gmail.com) 
"""
# Path to folder containing .xlsx files.
XLSX_FOLDER = r"*********"

# Source file name. Do not include ".xlsx".
INPUT_FILE_NAME = "*****"

# Output file name. Do not include ".xlsx".
OUTPUT_FILE_NAME = "*****"

# Chromosome number
CHROMOSOME = ""

# Select start sibling. Enter "Auto" if sibling with the fewest RPs is selected.
START_SIB = "Auto"

# Starting column for intial pass. 
START_COL = "H"
