# -*- coding: utf-8 -*-

"""
VP_html_Cousins_V2.py takes .html files from GEDmatch comparisons and attaches
them as cousins to .xlsx files generated by Visual_Phaser_New.


@author: Mick Jolley (email: mickj1948@gmail.com)


©2026 Michael E. Jolley

"""
import sys
import os
import shutil
from openpyxl import load_workbook
from openpyxl.styles import Border, Side, Alignment
from openpyxl.drawing.image import Image as XLImage
from PIL import Image
import matplotlib.image as mpimg

from VPHC_config_V2 import (
    WORKING_DIRECTORY,
    HTML_FOLDER,
    COUSINS,
    EXCEL_FILE_NAME,
    MAKE_BACKUP,
    SHOW_NO_MATCHES,
)

def get_paste_flag(pair, chrom, working_dir):
    """
    Determine whether a chromosome should be pasted based on the bar image.

    Reads the bar image for a pair/chromosome and checks the blue channel.
    If any pixel in the first row has blue intensity > 0.5, the pair is
    treated as having a match for that chromosome.

    @param pair: Pair identifier (e.g., "Name1-Name2")
    @type pair: str
    @param chrom: Chromosome number
    @type chrom: int
    @param working_dir: Path to the working directory
    @type working_dir: str
    @return: True when a match indicator is present, else False
    @rtype: bool
    """
    # Read Image
    img_path = os.path.join(working_dir, f"Bar {pair} {chrom}.png")
    img = mpimg.imread(img_path)

    # Separate blue channel.
    blue = img[0, :, 2]

    pflag = False

    for x in blue:
        if x > 0.5:
            pflag = True
            break

    return pflag

def delete_images(working_dir):
    """
    Remove temporary PNG images from the working directory.

    @param working_dir: Path to the working directory
    @type working_dir: str
    @return: No return value
    @rtype: None
    """
    files = os.listdir(working_dir)
    for images in files:
        if images.endswith(".png"):
            os.remove(os.path.join(working_dir, images))

def fill_sheets(matches, chromosomes, workbook, working_dir, show_no_matches):
    """
    Insert chromosome/bar images into workbook sheets for each match pair.

    Iterates through provided match names and chromosomes, conditionally pastes
    images based on show_no_matches/get_paste_flag, and applies alignment and
    border formatting.

    @param matches: Pair names to process
    @type matches: list[str]
    @param chromosomes: List of chromosome numbers
    @type chromosomes: list[int]
    @param workbook: The openpyxl workbook object
    @type workbook: openpyxl.workbook.workbook.Workbook
    @param working_dir: Path to the working directory
    @type working_dir: str
    @param show_no_matches: Flag to show chromosomes with no matches
    @type show_no_matches: bool
    @return: No return value
    @rtype: None
    """

    fflag = [True] * 24  # Size for up to Chr23

    for q, pair in enumerate(matches):
        for chrom in chromosomes:
            pflag = show_no_matches or get_paste_flag(pair, chrom, working_dir)
            if not pflag:
                continue

            ws = workbook[f"Chr{chrom}"]
            im_width = ws._images[1].width  
            last_col = ws.max_column - 1

            if q == 0 or fflag[chrom]:
                next_line = find_next_line(ws, 7, 3)
                fflag[chrom] = False
            else:
                next_line = find_next_line(ws, 7, 2)

            chr_img = XLImage(os.path.join(working_dir, f"Chr {pair} {chrom}.png"))
            chr_img.width = im_width
            chr_img.height = chr_img.height * 20
            ws.add_image(chr_img, ws.cell(next_line, 8).coordinate)

            ws.cell(next_line, 7).value = pair
            ws.cell(next_line, 7).alignment = Alignment(horizontal="center")

            bar_img = XLImage(os.path.join(working_dir, f"Bar {pair} {chrom}.png"))
            bar_img.width = im_width
            bar_img.height = bar_img.height * 15
            ws.add_image(bar_img, ws.cell(next_line + 1, 8).coordinate)

            if last_col is not None:
                add_borders(ws, last_col)

def add_borders(ws, col):
    """
    Add thick left borders to the image area in a worksheet.

    @param ws: Worksheet to update
    @type ws: openpyxl.worksheet.worksheet.Worksheet
    @param col: Last column index where border should be applied
    @type col: int
    @return: No return value
    @rtype: None
    """

    next_line = find_next_line(ws,7,3)

    side = Side(border_style="thick")
    border = Border(left=side)
    for i in range(1, next_line):
        for j in range(8, col+1):
            ws.cell(i, j).border = border

def find_next_line(ws, col, addn):
    """
    Find the next insertion row based on the last non-empty cell in a column.

    @param ws: Worksheet to scan
    @type ws: openpyxl.worksheet.worksheet.Worksheet
    @param col: Column index to inspect
    @type col: int
    @param addn: Offset added to last non-empty row
    @type addn: int
    @return: Next row number for insertion
    @rtype: int
    """

    lr = 0
    for i in range(1,1000):
        if ws.cell(i,col).value is not None:
            lr = i
    next_line = lr + addn

    return next_line

if __name__ == "__main__":
    html_folder = os.path.normpath(HTML_FOLDER)
    wdir = os.path.normpath(WORKING_DIRECTORY)

    xlfilnme = EXCEL_FILE_NAME

    # Get Excel file name.
    xlname = os.path.join(wdir, xlfilnme) + ".xlsx"
    
    if MAKE_BACKUP:
        # Create a backup copy before loading
        backup_name = xlname.replace(".xlsx", "_backup.xlsx")
        try:
            shutil.copy2(xlname, backup_name)
            print(f"\nBackup created: {backup_name}")
        except FileNotFoundError:
            print(f'File {xlname} does not exist. Enter an existing file.')
            sys.exit()
        except Exception as e:
            print(f'\nError creating backup: {e}')
            sys.exit()

    try:
        wb = load_workbook(xlname)
    except Exception as e:
        print(f'\nError loading workbook {xlname}: {e}')
        sys.exit()

    print("\nPlease wait while processing...")

    chroms = wb.sheetnames
    chromosomes = []
    siblings = []

    ws = wb[chroms[0]]

    for chrom_name in chroms:
        if not chrom_name[3:].isnumeric():
            continue
        if chrom_name != 'Chr23':
            chromosomes.append(int(chrom_name[3:]))

    for i in range(1,1000):
        if ws.cell(i,7).value is not None and ws.cell(i,7).value != 'Column Width':
            siblings.append(ws.cell(i,7).value)

    siblings = [name for name in siblings if '-' not in name]

    if not siblings:
        print('\nThere are no siblings to compare to.')
        sys.exit()

    match_pair_names = []

    for ind in siblings:
        for cousin in COUSINS:
            if ind != cousin:
                comb = (ind + '-' + cousin)
                match_pair_names.append(comb)

    for pair in match_pair_names:
        im_folder = os.path.join(html_folder, pair + '_files')
        
        if not os.path.exists(im_folder):
            print(f"Warning: Folder not found: {im_folder}")
            continue

        fil_list = os.listdir(im_folder)
        for im in fil_list:
            if im.endswith('.gif'):
                s = im.split('_')
                for chrom in chromosomes:
                    if s[2] == str(chrom):
                        if s[4] == '1.gif':
                            r = os.path.join(im_folder, im)
                            with Image.open(r) as img:
                                img.save(os.path.join(wdir, f"Chr {pair} {chrom}.png"))
                        else:
                            r = os.path.join(im_folder, im)
                            with Image.open(r) as img:
                                img.save(os.path.join(wdir, f"Bar {pair} {chrom}.png"))

    # Paste images to sheets
    fill_sheets(match_pair_names, chromosomes, wb, wdir, SHOW_NO_MATCHES)

    # Save workbook.
    wb.save(xlname)

    # Delete temporary images
    delete_images(wdir)


    print("\nFinished")

